import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/components/Navbar";
import NavbarLeft from "@/components/NavbarLeft";
import NavbarCenter from "@/components/NavbarCenter";
import NavbarRight from "@/components/NavbarRight";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
      <div>
        <div className='bg-amber-700 text-white flex justify-between'>
          <NavbarLeft/>
          <NavbarCenter/>
          <NavbarRight/>
        </div>
        {children}
      </div>
  );
}
